version: 0.2
phases:
  install:
    commands:
      - echo "Install Phase - Nothing to do using latest Amazon Linux Docker Image for CodeBuild which has all AWS Tools - https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/3.0/Dockerfile"
  pre_build:
      commands:
        # Verify AWS CLI Version        
        - echo "Verify AWS CLI Version..."
        - aws --version
        # Login to ECR Registry for docker to push the image to ECR Repository
        - echo "Login in to Amazon ECR..."
        - $(aws ecr get-login --no-include-email)
        # Update Kube config Home Directory
        - export KUBECONFIG=$HOME/.kube/config
  build:
    commands:
      # Build Docker Image
      - echo "Build started on `date`"
      - echo "Building the Docker image..."
      - docker build --tag 695013654214.dkr.ecr.us-east-2.amazonaws.com/hello-repository:latest .
  post_build:
    commands:
      # Push Docker Image to ECR Repository
      - echo "Build completed on `date`"
      - echo "Pushing the Docker image to ECR Repository"
      - docker push 695013654214.dkr.ecr.us-east-2.amazonaws.com/hello-repository
      - echo "Docker Image Push to ECR Completed -  695013654214.dkr.ecr.us-east-2.amazonaws.com/hello-repository"
      # Deploy Docker App to EKS
      - echo "Build completed on `date`"
      - echo "Delete the deployment image to ECR Repository"
      - kubectl delete deployment app-hola-mundo-deployment
      - kubectl delete service hola-mundo-service-load-balancer
      - echo "Deploying the Docker image to ECR Repository"
      - kubectl apply -f hola-mundo-v2.yaml
      - echo "Deploying the Docker service to expose app"
      - kubectl expose deployment app-hola-mundo-deployment  --type=LoadBalancer  --name=hola-mundo-service-load-balancer
      - echo "Docker Deploy Push to ECR Completed"
